env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
  - plugin:vue/vue3-essential
  - plugin:prettier/recommended
  # - .eslintrc-auto-import.json
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - vue
# ts 全局类型声明（如果不加此项那么 eslint 就会报错）
globals:
  Table: true
  API: true
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    -
      varsIgnorePattern: .*
      args: none

  '@typescript-eslint/no-explicit-any': off

  vue/component-definition-name-casing:
    - error
    - kebab-case

  vue/component-options-name-casing:
    - error
    - kebab-case

  linebreak-style:
    - 0
    - windows

  prettier/prettier:
    - error
    -
      endOfLine: auto

  vue/require-default-prop: off

  vue/multi-word-component-names:
    - warn
    -
      ignores:
        - index
        - layout
        - users
        - login
        - menus
        - table
        - body
        - col
        - head
        - expand
        - home
        - sort
