# @prettier

printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: always
rangeStart: 0
requirePragma: false
insertPragma: false
proseWrap: preserve
htmlWhitespaceSensitivity: ignore
vueIndentScriptAndStyle: false
singleAttributePerLine: true
endOfline: auto
